{% set name = "fml" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fwilliams/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 24891fbe9151cf1222d41d5cd53867b1f2cc01e6fc3f12f968b0ab19705c172f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pytorch

test:
  requires:
    - python {{ python_min }}
  imports:
    - fml

about:
  home: https://github.com/fwilliams/fml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "FML (Francis' Machine-Learnin' Library) - A collection of PyTorch tools for machine learning."
  dev_url: https://github.com/fwilliams/fml

extra:
  recipe-maintainers:
    - fwilliams
