travis:
  secure:
    BINSTAR_TOKEN: f9mHYvDWqhlV8G6Anba1LDvOZQ5yiiVKw+3pgZpxMO5Ekig6xxNZv9i3S97rgoEeEkyuBSi89ixcElw3g0RMAqY5B88unZCexi7HnFqzDRtCimY854EM0UlMV2d6pU+arGPqptkomka2tKTd871P8WL39gGO1d2gr0fiqVSgrF9nZ1mGpVZPT7aBHXS/UpKVjblamrY0tnwmZXulFSE4/N9jWyk6/znJmZxprAAofLQBB8IMUvIn2nMHAeM3r0RZfwkNdjIVj9a+EI6IrJkxavXxa1l/HEQ5RTDnaBnWaShYYnyOh7lj19FgG025gH46fS4+z+89N2m2BEgXPcWFU3sOsSDQdnLbgkP5gnST1rTdOw6Le/GsKyJyJFqyhQljmi+VPiZflGuLnpMuXn7sTKDtwGre2aS7ztjBt3vE7Bc8h/FtPQ365PxiQQLzUG+boJviSCnERf5JJR3afoSL4NGiHy0AMcbSZR+cTljvcY7278l3ZFL4lr5Fwiptv5Xza3yr+asp+Wj0UZ0lmfphmZzyKaOjclT9igPcDO94V6Jxx+M1DcC3Bjj/NYdvG5G2fjViOGwNFugoM2RWy9MmmULs8rsNcFlAWz18y1YMb5KMnQ20lpw2dor3LP2c8bnPOa7NF0+jLAi0uiM9EtZytgjL/IFXbi38gpKeEQb7x3Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
